package io.github.kdroidfilter.nucleus.sfsymbols

/** SF Symbols — Time (45 symbols). */
enum class SFSymbolTime(
    override val symbolName: String,
) : SFSymbol {
    ALARM("alarm"),
    ALARM_FILL("alarm.fill"),
    ALARM_WAVES_LEFT_AND_RIGHT("alarm.waves.left.and.right"),
    ALARM_WAVES_LEFT_AND_RIGHT_FILL("alarm.waves.left.and.right.fill"),
    CALENDAR("calendar"),
    CALENDAR_AND_PERSON("calendar.and.person"),
    CALENDAR_BADGE_CHECKMARK("calendar.badge.checkmark"),
    CALENDAR_BADGE_CLOCK("calendar.badge.clock"),
    CALENDAR_BADGE_EXCLAMATIONMARK("calendar.badge.exclamationmark"),
    CALENDAR_BADGE_MINUS("calendar.badge.minus"),
    CALENDAR_BADGE_PLUS("calendar.badge.plus"),
    CALENDAR_CIRCLE("calendar.circle"),
    CALENDAR_CIRCLE_FILL("calendar.circle.fill"),
    CALENDAR_DAY_TIMELINE_LEADING("calendar.day.timeline.leading"),
    CALENDAR_DAY_TIMELINE_LEFT("calendar.day.timeline.left"),
    CALENDAR_DAY_TIMELINE_RIGHT("calendar.day.timeline.right"),
    CALENDAR_DAY_TIMELINE_TRAILING("calendar.day.timeline.trailing"),
    CLOCK("clock"),
    CLOCK_ARROW_TRIANGLEHEAD_2_COUNTERCLOCKWISE_ROTATE_90("clock.arrow.trianglehead.2.counterclockwise.rotate.90"),
    CLOCK_ARROW_TRIANGLEHEAD_COUNTERCLOCKWISE_ROTATE_90("clock.arrow.trianglehead.counterclockwise.rotate.90"),
    CLOCK_BADGE("clock.badge"),
    CLOCK_BADGE_CHECKMARK("clock.badge.checkmark"),
    CLOCK_BADGE_CHECKMARK_FILL("clock.badge.checkmark.fill"),
    CLOCK_BADGE_EXCLAMATIONMARK("clock.badge.exclamationmark"),
    CLOCK_BADGE_EXCLAMATIONMARK_FILL("clock.badge.exclamationmark.fill"),
    CLOCK_BADGE_FILL("clock.badge.fill"),
    CLOCK_BADGE_QUESTIONMARK("clock.badge.questionmark"),
    CLOCK_BADGE_QUESTIONMARK_FILL("clock.badge.questionmark.fill"),
    CLOCK_BADGE_XMARK("clock.badge.xmark"),
    CLOCK_BADGE_XMARK_FILL("clock.badge.xmark.fill"),
    CLOCK_CIRCLE("clock.circle"),
    CLOCK_CIRCLE_FILL("clock.circle.fill"),
    CLOCK_FILL("clock.fill"),
    HOURGLASS("hourglass"),
    HOURGLASS_AND_LOCK("hourglass.and.lock"),
    HOURGLASS_BADGE_EYE("hourglass.badge.eye"),
    HOURGLASS_BADGE_PLUS("hourglass.badge.plus"),
    HOURGLASS_BOTTOMHALF_FILLED("hourglass.bottomhalf.filled"),
    HOURGLASS_CIRCLE("hourglass.circle"),
    HOURGLASS_CIRCLE_FILL("hourglass.circle.fill"),
    HOURGLASS_TOPHALF_FILLED("hourglass.tophalf.filled"),
    TIMER("timer"),
    TIMER_CIRCLE("timer.circle"),
    TIMER_CIRCLE_FILL("timer.circle.fill"),
    TIMER_SQUARE("timer.square"),
}
