package io.github.kdroidfilter.nucleus.sfsymbols

/** SF Symbols — Location (47 symbols). */
enum class SFSymbolLocation(
    override val symbolName: String,
) : SFSymbol {
    COMPASS_DRAWING("compass.drawing"),
    FLAG("flag"),
    FLAG_2_CROSSED("flag.2.crossed"),
    FLAG_2_CROSSED_CIRCLE("flag.2.crossed.circle"),
    FLAG_2_CROSSED_CIRCLE_FILL("flag.2.crossed.circle.fill"),
    FLAG_2_CROSSED_FILL("flag.2.crossed.fill"),
    FLAG_AND_FLAG_FILLED_CROSSED("flag.and.flag.filled.crossed"),
    FLAG_BADGE_ELLIPSIS("flag.badge.ellipsis"),
    FLAG_BADGE_ELLIPSIS_FILL("flag.badge.ellipsis.fill"),
    FLAG_CIRCLE("flag.circle"),
    FLAG_CIRCLE_FILL("flag.circle.fill"),
    FLAG_FILL("flag.fill"),
    FLAG_FILLED_AND_FLAG_CROSSED("flag.filled.and.flag.crossed"),
    FLAG_PATTERN_CHECKERED("flag.pattern.checkered"),
    FLAG_PATTERN_CHECKERED_2_CROSSED("flag.pattern.checkered.2.crossed"),
    FLAG_PATTERN_CHECKERED_CIRCLE("flag.pattern.checkered.circle"),
    FLAG_PATTERN_CHECKERED_CIRCLE_FILL("flag.pattern.checkered.circle.fill"),
    FLAG_SLASH("flag.slash"),
    FLAG_SLASH_CIRCLE("flag.slash.circle"),
    FLAG_SLASH_CIRCLE_FILL("flag.slash.circle.fill"),
    FLAG_SLASH_FILL("flag.slash.fill"),
    FLAG_SQUARE("flag.square"),
    FLAG_SQUARE_FILL("flag.square.fill"),
    LOCATION("location"),
    LOCATION_APP("location.app"),
    LOCATION_APP_FILL("location.app.fill"),
    LOCATION_CIRCLE("location.circle"),
    LOCATION_CIRCLE_FILL("location.circle.fill"),
    LOCATION_FILL("location.fill"),
    LOCATION_FILL_VIEWFINDER("location.fill.viewfinder"),
    LOCATION_MAGNIFYINGGLASS("location.magnifyingglass"),
    LOCATION_NORTH("location.north"),
    LOCATION_NORTH_CIRCLE("location.north.circle"),
    LOCATION_NORTH_CIRCLE_FILL("location.north.circle.fill"),
    LOCATION_NORTH_FILL("location.north.fill"),
    LOCATION_NORTH_LINE("location.north.line"),
    LOCATION_NORTH_LINE_FILL("location.north.line.fill"),
    LOCATION_SLASH("location.slash"),
    LOCATION_SLASH_CIRCLE("location.slash.circle"),
    LOCATION_SLASH_CIRCLE_FILL("location.slash.circle.fill"),
    LOCATION_SLASH_FILL("location.slash.fill"),
    LOCATION_SQUARE("location.square"),
    LOCATION_SQUARE_FILL("location.square.fill"),
    LOCATION_VIEWFINDER("location.viewfinder"),
    SAFARI("safari"),
    SAFARI_FILL("safari.fill"),
    SCOPE("scope"),
}
