package io.github.kdroidfilter.nucleus.sfsymbols

/** SF Symbols — Health (57 symbols). */
enum class SFSymbolHealth(
    override val symbolName: String,
) : SFSymbol {
    ALLERGENS("allergens"),
    ALLERGENS_FILL("allergens.fill"),
    BASEBALL("baseball"),
    BASEBALL_CIRCLE("baseball.circle"),
    BASEBALL_CIRCLE_FILL("baseball.circle.fill"),
    BASEBALL_DIAMOND_BASES("baseball.diamond.bases"),
    BASEBALL_DIAMOND_BASES_OUTS_INDICATOR("baseball.diamond.bases.outs.indicator"),
    BASEBALL_FILL("baseball.fill"),
    BASKETBALL("basketball"),
    BASKETBALL_CIRCLE("basketball.circle"),
    BASKETBALL_CIRCLE_FILL("basketball.circle.fill"),
    BASKETBALL_FILL("basketball.fill"),
    CRICKET_BALL("cricket.ball"),
    CRICKET_BALL_CIRCLE("cricket.ball.circle"),
    CRICKET_BALL_CIRCLE_FILL("cricket.ball.circle.fill"),
    CRICKET_BALL_FILL("cricket.ball.fill"),
    DUMBBELL("dumbbell"),
    DUMBBELL_FILL("dumbbell.fill"),
    HOCKEY_PUCK("hockey.puck"),
    HOCKEY_PUCK_CIRCLE("hockey.puck.circle"),
    HOCKEY_PUCK_CIRCLE_FILL("hockey.puck.circle.fill"),
    HOCKEY_PUCK_FILL("hockey.puck.fill"),
    MEDICAL_THERMOMETER("medical.thermometer"),
    MEDICAL_THERMOMETER_FILL("medical.thermometer.fill"),
    RUGBYBALL("rugbyball"),
    RUGBYBALL_CIRCLE("rugbyball.circle"),
    RUGBYBALL_CIRCLE_FILL("rugbyball.circle.fill"),
    RUGBYBALL_FILL("rugbyball.fill"),
    SOCCERBALL("soccerball"),
    SOCCERBALL_CIRCLE("soccerball.circle"),
    SOCCERBALL_CIRCLE_FILL("soccerball.circle.fill"),
    SOCCERBALL_CIRCLE_FILL_INVERSE("soccerball.circle.fill.inverse"),
    SOCCERBALL_CIRCLE_INVERSE("soccerball.circle.inverse"),
    SOCCERBALL_INVERSE("soccerball.inverse"),
    SPORTSCOURT("sportscourt"),
    SPORTSCOURT_CIRCLE("sportscourt.circle"),
    SPORTSCOURT_CIRCLE_FILL("sportscourt.circle.fill"),
    SPORTSCOURT_FILL("sportscourt.fill"),
    STETHOSCOPE("stethoscope"),
    STETHOSCOPE_CIRCLE("stethoscope.circle"),
    STETHOSCOPE_CIRCLE_FILL("stethoscope.circle.fill"),
    TENNIS_RACKET("tennis.racket"),
    TENNIS_RACKET_CIRCLE("tennis.racket.circle"),
    TENNIS_RACKET_CIRCLE_FILL("tennis.racket.circle.fill"),
    TENNISBALL("tennisball"),
    TENNISBALL_CIRCLE("tennisball.circle"),
    TENNISBALL_CIRCLE_FILL("tennisball.circle.fill"),
    TENNISBALL_FILL("tennisball.fill"),
    VOLLEYBALL("volleyball"),
    VOLLEYBALL_CIRCLE("volleyball.circle"),
    VOLLEYBALL_CIRCLE_FILL("volleyball.circle.fill"),
    VOLLEYBALL_FILL("volleyball.fill"),
    WATER_WAVES("water.waves"),
    WATER_WAVES_AND_ARROW_TRIANGLEHEAD_DOWN("water.waves.and.arrow.trianglehead.down"),
    WATER_WAVES_AND_ARROW_TRIANGLEHEAD_DOWN_TRIANGLEBADGE_EXCLAMATIONMARK(
        "water.waves.and.arrow.trianglehead.down.trianglebadge.exclamationmark",
    ),
    WATER_WAVES_AND_ARROW_TRIANGLEHEAD_UP("water.waves.and.arrow.trianglehead.up"),
    WATER_WAVES_SLASH("water.waves.slash"),
}
