Args = -H:+UnlockExperimentalVMOptions \
       -H:+SharedArenaSupport \
       -H:IncludeResources=.*\\.(svg|ttf|otf) \
       -H:IncludeResources=nucleus/.* \
       -H:IncludeResources=META-INF/services/.* \
       -H:IncludeResources=composeResources/.*
