name: Test GraalVM Native Image

on:
  pull_request:
    branches:
      - '*'

concurrency:
  group: test-graalvm-${{ github.head_ref || github.ref }}
  cancel-in-progress: true

jobs:
  build-natives:
    uses: ./.github/workflows/build-natives.yaml

  graalvm:
    needs: build-natives
    name: GraalVM - ${{ matrix.name }}
    runs-on: ${{ matrix.os }}
    timeout-minutes: 30
    strategy:
      fail-fast: false
      matrix:
        include:
          - name: Linux x64
            os: ubuntu-latest
          - name: macOS ARM64
            os: macos-latest
          - name: Windows x64
            os: windows-latest

    steps:
      - name: Checkout Repo
        uses: actions/checkout@v4

      - name: Download darkmode-detector native artifacts
        uses: actions/download-artifact@v4
        with:
          path: darkmode-detector/src/main/resources/nucleus/native/
          pattern: '*-natives*'
          merge-multiple: true

      - name: Download native-ssl artifacts
        uses: actions/download-artifact@v4
        with:
          path: native-ssl/src/main/resources/nucleus/native/
          pattern: 'ssl-*'
          merge-multiple: true

      - name: Download decorated-window-jbr artifacts
        uses: actions/download-artifact@v4
        with:
          path: decorated-window-jbr/src/main/resources/nucleus/native/
          pattern: 'decorated-window-jbr-*'
          merge-multiple: true

      - name: Download decorated-window-jni artifacts
        uses: actions/download-artifact@v4
        with:
          path: decorated-window-jni/src/main/resources/nucleus/native/
          pattern: 'decorated-window-jni-*'
          merge-multiple: true

      - name: Download linux-hidpi artifacts
        uses: actions/download-artifact@v4
        with:
          path: linux-hidpi/src/main/resources/nucleus/native/
          pattern: 'linux-hidpi-*'
          merge-multiple: true

      - name: Download energy-manager artifacts
        uses: actions/download-artifact@v4
        with:
          path: energy-manager/src/main/resources/nucleus/native/
          pattern: 'energy-manager-*'
          merge-multiple: true

      - name: Setup Nucleus (GraalVM)
        uses: ./.github/actions/setup-nucleus
        with:
          graalvm: 'true'
          setup-gradle: 'true'
          setup-node: 'false'

      - name: Build GraalVM native image
        shell: bash
        run: ./gradlew :example:packageGraalvmNative -PnativeMarch=compatibility --no-daemon --stacktrace

      - name: Upload GraalVM artifacts
        if: always()
        uses: actions/upload-artifact@v4
        with:
          name: graalvm-${{ runner.os }}
          path: |
            example/build/compose/tmp/**/graalvm/output/**
          if-no-files-found: warn
